name: "Setup Ren'Py environment"
description: "Set up your GitHub Actions workflow with a specific version of Ren'Py"
author: "Proudust"

inputs:
  renpy-version:
    description: "Version Spec of the version to use.  Examples: 6.99.12.4"
    required: true

outputs:
  launcher:
    description: "Ren'Py SDK launcher project directory"

runs:
  using: "node12"
  main: "dist/index.js"
